export type TemplateCategory = 'feedback' | 'payments' | 'orders';

export interface LibraryButton {
    type: 'QUICK_REPLY';
    text: string;
}

export interface LibraryTemplate {
    id: string;
    category: TemplateCategory;
    subcategory: string;
    displayName: string;
    subcategoryDisplayName: string;
    body: string;
    variableLabels: string[];
    headerType: 'NONE' | 'IMAGE' | 'DOCUMENT';
    buttons: LibraryButton[];
    suggestedName: string;
    metaCategory?: 'UTILITY' | 'MARKETING' | 'AUTHENTICATION';
}

export interface CategoryMeta {
    id: TemplateCategory;
    label: string;
    emoji: string;
    subcategories: { id: string; label: string }[];
}

export const CATEGORIES: CategoryMeta[] = [
    {
        id: 'feedback',
        label: 'Feedback do Cliente',
        emoji: '⭐',
        subcategories: [
            { id: 'feedback_survey',        label: 'Pesquisa de feedback' },
            { id: 'missed_call_followup',   label: 'Acompanhar ligações não atendidas' },
            { id: 'ticket_confirmation',    label: 'Confirmação de tíquete' },
        ],
    },
    {
        id: 'payments',
        label: 'Pagamentos',
        emoji: '💳',
        subcategories: [
            { id: 'auto_pay_reminder',        label: 'Lembrete de pagamento automático' },
            { id: 'transaction_alert',         label: 'Alerta de transação' },
            { id: 'fraud_alert',               label: 'Alerta de fraude' },
            { id: 'low_balance',               label: 'Aviso de saldo baixo' },
            { id: 'payment_action_required',   label: 'Ação necessária no pagamento' },
            { id: 'payment_confirmation',      label: 'Confirmação de pagamento' },
            { id: 'payment_due_reminder',      label: 'Lembrete de pagamento vencido' },
            { id: 'payment_failed',            label: 'Rejeição/falha no pagamento' },
            { id: 'payment_notice',            label: 'Aviso de pagamento' },
            { id: 'late_payment',              label: 'Pagamento em atraso' },
            { id: 'scheduled_payment',         label: 'Pagamento programado' },
            { id: 'payment_success',           label: 'Pagamento realizado com sucesso' },
            { id: 'receipt_attachment',        label: 'Anexo de recibo' },
            { id: 'topup_failure',             label: 'Rejeição/falha na recarga' },
            { id: 'topup_confirmation',        label: 'Confirmação de recarga' },
            { id: 'statement_available',       label: 'Extrato disponível' },
        ],
    },
    {
        id: 'orders',
        label: 'Gerenciamento de Pedidos',
        emoji: '📦',
        subcategories: [
            { id: 'delivery_update',        label: 'Atualização sobre a entrega' },
            { id: 'delivery_confirmation',  label: 'Confirmação de entrega' },
            { id: 'delivery_failure',       label: 'Falha na entrega' },
            { id: 'return_confirmation',    label: 'Confirmação de devolução' },
            { id: 'order_confirmation',     label: 'Confirmação do pedido' },
            { id: 'order_action',           label: 'Ação necessária no pedido' },
            { id: 'order_cancellation',     label: 'Cancelar pedido ou transação' },
            { id: 'order_delay',            label: 'Atraso no pedido' },
            { id: 'order_pickup',           label: 'Retirada do pedido' },
            { id: 'shipping_confirmation',  label: 'Confirmação de envio' },
            { id: 'order_refund',           label: 'Reembolso do pedido' },
        ],
    },
];

export const LIBRARY_TEMPLATES: LibraryTemplate[] = [
    // ── FEEDBACK DO CLIENTE: Pesquisa de feedback ────
    {
        id: 'feedback_collection',
        category: 'feedback',
        subcategory: 'feedback_survey',
        displayName: 'Coleta de Feedback Pós-Serviço',
        subcategoryDisplayName: 'Pesquisa de feedback',
        body: 'Olá, {{1}}, o pedido de serviço que concluímos em {{2}} está encerrado. Classifique sua experiência de 1-5 e compartilhe qualquer feedback para nos ajudar a melhorar.',
        variableLabels: ['nome do cliente', 'data de conclusão'],
        headerType: 'NONE',
        buttons: [],
        suggestedName: 'coleta_feedback_pos_servico',
        metaCategory: 'MARKETING',
    },
    {
        id: 'feedback_survey_1',
        category: 'feedback',
        subcategory: 'feedback_survey',
        displayName: 'Pesquisa de Satisfação #1',
        subcategoryDisplayName: 'Pesquisa de feedback',
        body: 'Olá, {{1}}. Obrigado por sua recente {{2}} em {{3}}. Nós valorizamos o seu feedback e gostaríamos que compartilhasse mais sobre a sua experiência conosco no link abaixo. Isto deve demorar apenas {{4}} minutos. Agradecemos o seu tempo.',
        variableLabels: ['nome do cliente', 'compra/visita/consulta', 'empresa/loja', 'número de minutos'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Deixe feedback' }],
        suggestedName: 'pesquisa_satisfacao_1',
        metaCategory: 'MARKETING',
    },
    {
        id: 'feedback_survey_2',
        category: 'feedback',
        subcategory: 'feedback_survey',
        displayName: 'Pesquisa de Satisfação #2',
        subcategoryDisplayName: 'Pesquisa de feedback',
        body: 'Como foi a sua experiência? Agradecemos por nos visitar em {{1}} no dia {{2}}. Seu feedback é importante para nós. Responda a esta pesquisa breve para nos informar como podemos melhorar.',
        variableLabels: ['empresa/loja', 'data da visita'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Preencher pesquisa' }],
        suggestedName: 'pesquisa_satisfacao_2',
        metaCategory: 'MARKETING',
    },
    {
        id: 'feedback_survey_form_1',
        category: 'feedback',
        subcategory: 'feedback_survey',
        displayName: 'Formulário de Avaliação #1',
        subcategoryDisplayName: 'Pesquisa de feedback',
        body: 'Classifique sua experiência. Seu feedback é importante para nós. Responda a uma pesquisa rápida sobre sua experiência recente com a {{1}}.',
        variableLabels: ['empresa/marca'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Responder à pesquisa' }],
        suggestedName: 'formulario_avaliacao_1',
        metaCategory: 'MARKETING',
    },
    {
        id: 'feedback_survey_form_2',
        category: 'feedback',
        subcategory: 'feedback_survey',
        displayName: 'Formulário de Avaliação #2',
        subcategoryDisplayName: 'Pesquisa de feedback',
        body: 'O feedback dos clientes é importante para o {{1}}. Ele é usado para melhorarmos nossos {{2}} de forma contínua. Preencha uma {{3}} breve (link abaixo) para nos contar como foi a {{4}} recente que fez conosco. Desde já agradecemos.',
        variableLabels: ['empresa', 'produtos/serviços', 'pesquisa', 'compra/visita/consulta'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Responder à pesquisa' }],
        suggestedName: 'formulario_avaliacao_2',
        metaCategory: 'MARKETING',
    },

    // ── FEEDBACK DO CLIENTE: Ligações não atendidas ──
    {
        id: 'missed_call_followup_1',
        category: 'feedback',
        subcategory: 'missed_call_followup',
        displayName: 'Acompanhar Ligação Perdida',
        subcategoryDisplayName: 'Acompanhar ligações não atendidas',
        body: 'Olá, {{1}}. Tentamos entrar em contato com você recentemente, mas não conseguimos falar. Como podemos ajudar? Responda esta mensagem ou ligue para {{2}} no horário comercial.',
        variableLabels: ['nome do cliente', 'número de contato'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ligar agora' }],
        suggestedName: 'acompanhar_ligacao_perdida',
        metaCategory: 'UTILITY',
    },

    // ── FEEDBACK DO CLIENTE: Confirmação de tíquete ──
    {
        id: 'ticket_confirmation_1',
        category: 'feedback',
        subcategory: 'ticket_confirmation',
        displayName: 'Confirmação de Tíquete de Suporte',
        subcategoryDisplayName: 'Confirmação de tíquete',
        body: 'Olá, {{1}}. Seu tíquete de suporte *#{{2}}* foi aberto com sucesso. Nossa equipe entrará em contato em até {{3}} horas úteis. Você pode acompanhar o status pelo link abaixo.',
        variableLabels: ['nome do cliente', 'número do tíquete', 'prazo em horas'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver status do tíquete' }],
        suggestedName: 'confirmacao_tiquete_suporte',
        metaCategory: 'UTILITY',
    },

    // ── PAGAMENTOS: Lembrete automático ──────────────
    {
        id: 'auto_pay_reminder_1',
        category: 'payments',
        subcategory: 'auto_pay_reminder',
        displayName: 'Lembrete de Débito Automático #1',
        subcategoryDisplayName: 'Lembrete de pagamento automático',
        body: 'Oi, {{1}},\n\nSeu pagamento automático para a {{2}} está programado para o dia {{3}} no valor de {{4}}.\n\nConfira se o seu saldo é suficiente para evitar cobranças {{5}}.',
        variableLabels: ['nome do cliente', 'empresa/conta', 'data', 'valor', 'adicionais (ex: extras)'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver conta' }],
        suggestedName: 'lembrete_debito_automatico_1',
    },
    {
        id: 'auto_pay_reminder_2',
        category: 'payments',
        subcategory: 'auto_pay_reminder',
        displayName: 'Lembrete de Débito Automático #2',
        subcategoryDisplayName: 'Lembrete de pagamento automático',
        body: 'Oi, {{1}}, este é um lembrete de que seu pagamento automático está chegando:\n\nData: {{2}}\nConta: {{3}}\nValor: {{4}}\n\nTenha um ótimo dia.',
        variableLabels: ['nome do cliente', 'data de débito', 'conta', 'valor'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver detalhes' }],
        suggestedName: 'lembrete_debito_automatico_2',
    },

    {
        id: 'auto_pay_reminder_3',
        category: 'payments',
        subcategory: 'auto_pay_reminder',
        displayName: 'Lembrete de Débito Automático #3',
        subcategoryDisplayName: 'Lembrete de pagamento automático',
        body: 'Lembrete:\n\nSeu pagamento programado do cartão {{1}} com final {{2}} está agendado para {{3}}.\n\nObrigado.',
        variableLabels: ['tipo de cartão', 'final do cartão', 'data'],
        headerType: 'NONE',
        buttons: [],
        suggestedName: 'lembrete_debito_automatico_3',
    },

    // ── PAGAMENTOS: Alerta de transação ──────────────
    {
        id: 'transaction_alert_1',
        category: 'payments',
        subcategory: 'transaction_alert',
        displayName: 'Transação Realizada #1',
        subcategoryDisplayName: 'Alerta de transação',
        body: 'Olá {{1}}, uma transação de {{2}} foi realizada na sua conta {{3}} em {{4}}.\n\nNão reconhece? Entre em contato imediatamente.',
        variableLabels: ['nome do cliente', 'valor', 'conta/cartão', 'data e hora'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver transação' }],
        suggestedName: 'alerta_transacao_1',
    },
    {
        id: 'transaction_alert_2',
        category: 'payments',
        subcategory: 'transaction_alert',
        displayName: 'Transação Realizada #2',
        subcategoryDisplayName: 'Alerta de transação',
        body: 'Alerta de transação:\n\nCartão: {{1}}\nValor: {{2}}\nEstabelecimento: {{3}}\nData: {{4}}\n\nSe não reconhecer, bloqueie imediatamente.',
        variableLabels: ['final do cartão', 'valor', 'estabelecimento', 'data e hora'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Bloquear cartão' }],
        suggestedName: 'alerta_transacao_2',
    },
    {
        id: 'transaction_alert_3',
        category: 'payments',
        subcategory: 'transaction_alert',
        displayName: 'Débito na Conta',
        subcategoryDisplayName: 'Alerta de transação',
        body: 'Olá {{1}}, um débito de {{2}} foi lançado na sua conta em {{3}}.\n\nSaldo disponível: {{4}}.',
        variableLabels: ['nome do cliente', 'valor', 'data', 'saldo restante'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver conta' }],
        suggestedName: 'alerta_debito_conta',
    },

    // ── PAGAMENTOS: Alerta de fraude ─────────────────
    {
        id: 'fraud_alert_1',
        category: 'payments',
        subcategory: 'fraud_alert',
        displayName: 'Atividade Suspeita Detectada',
        subcategoryDisplayName: 'Alerta de fraude',
        body: 'Olá {{1}}, detectamos uma atividade suspeita no seu cartão {{2}}.\n\nSe não foi você, bloqueie agora e entre em contato conosco.',
        variableLabels: ['nome do cliente', 'final do cartão'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Bloquear cartão' }],
        suggestedName: 'alerta_fraude_1',
    },
    {
        id: 'fraud_alert_2',
        category: 'payments',
        subcategory: 'fraud_alert',
        displayName: 'Tentativa de Fraude Bloqueada',
        subcategoryDisplayName: 'Alerta de fraude',
        body: 'Alerta de segurança, {{1}}!\n\nBloqueamos uma tentativa suspeita de {{2}} no seu cartão {{3}} em {{4}}.\n\nSeu cartão está seguro. Confirme se foi você.',
        variableLabels: ['nome do cliente', 'valor', 'final do cartão', 'data e hora'],
        headerType: 'NONE',
        buttons: [
            { type: 'QUICK_REPLY', text: 'Fui eu' },
            { type: 'QUICK_REPLY', text: 'Não fui eu' },
        ],
        suggestedName: 'alerta_fraude_2',
    },
    {
        id: 'fraud_alert_3',
        category: 'payments',
        subcategory: 'fraud_alert',
        displayName: 'Verificação de Segurança',
        subcategoryDisplayName: 'Alerta de fraude',
        body: 'Por segurança, sua conta {{1}} foi temporariamente suspensa devido a atividade incomum.\n\nAcesse abaixo para verificar e reativar.',
        variableLabels: ['número/nome da conta'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Verificar conta' }],
        suggestedName: 'alerta_fraude_verificacao',
    },
    {
        id: 'fraud_alert_4',
        category: 'payments',
        subcategory: 'fraud_alert',
        displayName: 'Confirmação de Transação Suspeita',
        subcategoryDisplayName: 'Alerta de fraude',
        body: 'Olá {{1}}, há uma tentativa de transação de {{2}} na sua conta.\n\nSe foi você, confirme abaixo. Caso contrário, negue imediatamente.',
        variableLabels: ['nome do cliente', 'valor'],
        headerType: 'NONE',
        buttons: [
            { type: 'QUICK_REPLY', text: 'Confirmar' },
            { type: 'QUICK_REPLY', text: 'Negar' },
        ],
        suggestedName: 'confirmacao_transacao_suspeita',
    },

    // ── PAGAMENTOS: Aviso de saldo baixo ─────────────
    {
        id: 'low_balance_1',
        category: 'payments',
        subcategory: 'low_balance',
        displayName: 'Saldo Baixo — Recarga Necessária',
        subcategoryDisplayName: 'Aviso de saldo baixo',
        body: 'Olá {{1}}, seu saldo atual é de {{2}}.\n\nRecarregue agora para evitar interrupções no serviço.',
        variableLabels: ['nome do cliente', 'saldo atual'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Recarregar' }],
        suggestedName: 'aviso_saldo_baixo_1',
    },
    {
        id: 'low_balance_2',
        category: 'payments',
        subcategory: 'low_balance',
        displayName: 'Saldo Baixo — Pagamento Pendente',
        subcategoryDisplayName: 'Aviso de saldo baixo',
        body: 'Atenção, {{1}}! Seu saldo em {{2}} está baixo ({{3}}) e há um pagamento de {{4}} previsto para {{5}}.\n\nDepositar agora evita cobranças adicionais.',
        variableLabels: ['nome do cliente', 'conta', 'saldo atual', 'valor do débito', 'data'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Depositar agora' }],
        suggestedName: 'aviso_saldo_baixo_2',
    },
    {
        id: 'low_balance_3',
        category: 'payments',
        subcategory: 'low_balance',
        displayName: 'Saldo Abaixo do Mínimo',
        subcategoryDisplayName: 'Aviso de saldo baixo',
        body: 'Olá {{1}}, seu saldo ({{2}}) está abaixo do mínimo exigido de {{3}} na conta {{4}}.\n\nDepositar até {{5}} evita tarifas.',
        variableLabels: ['nome do cliente', 'saldo atual', 'saldo mínimo', 'número da conta', 'data limite'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver conta' }],
        suggestedName: 'aviso_saldo_minimo',
    },

    // ── PAGAMENTOS: Ação necessária ───────────────────
    {
        id: 'payment_action_required_1',
        category: 'payments',
        subcategory: 'payment_action_required',
        displayName: 'Verificar Informações de Pagamento',
        subcategoryDisplayName: 'Ação necessária no pagamento',
        body: 'Oi, {{1}},\n\nO pagamento do seu cartão {{2}} com final {{3}} está chegando.\n\nVerifique suas informações para evitar cobranças {{4}}.\nSe você já pagou, ignore esta mensagem.',
        variableLabels: ['nome do cliente', 'tipo de cartão', 'final do cartão', 'adicionais'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Verificar' }],
        suggestedName: 'verificar_info_pagamento',
    },

    // ── PAGAMENTOS: Confirmação ───────────────────────
    {
        id: 'payment_confirmation_1',
        category: 'payments',
        subcategory: 'payment_confirmation',
        displayName: 'Confirmação de Pagamento #1',
        subcategoryDisplayName: 'Confirmação de pagamento',
        body: 'Oi, {{1}},\n\nRecebemos seu pagamento de {{2}} para o {{3}}.\n\nAgradecemos seu pagamento.',
        variableLabels: ['nome do cliente', 'valor', 'conta/serviço'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver detalhes de pagamento' }],
        suggestedName: 'confirmacao_pagamento_1',
    },
    {
        id: 'payment_confirmation_2',
        category: 'payments',
        subcategory: 'payment_confirmation',
        displayName: 'Confirmação de Pagamento #2',
        subcategoryDisplayName: 'Confirmação de pagamento',
        body: 'Seu pagamento no valor de {{1}} para o {{2}} foi processado com sucesso.\n\nAgradecemos por fazer negócios conosco.',
        variableLabels: ['valor', 'conta/serviço'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver detalhes' }],
        suggestedName: 'confirmacao_pagamento_2',
    },

    // ── PAGAMENTOS: Lembrete de vencimento ───────────
    {
        id: 'payment_due_reminder',
        category: 'payments',
        subcategory: 'payment_due_reminder',
        displayName: 'Pagamento Próximo do Vencimento',
        subcategoryDisplayName: 'Lembrete de pagamento vencido',
        body: 'Olá, {{1}}, a sua conta {{2}} de {{3}} deve ser vencida em {{4}}. Pague agora para evitar interrupções no serviço.\nIgnore se já tiver pago.',
        variableLabels: ['nome do cliente', 'número/nome da conta', 'valor', 'data de vencimento'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Pagar agora' }],
        suggestedName: 'pagamento_proximo_vencimento',
    },
    {
        id: 'payment_due_reminder_1',
        category: 'payments',
        subcategory: 'payment_due_reminder',
        displayName: 'Fatura Próxima do Vencimento',
        subcategoryDisplayName: 'Lembrete de pagamento vencido',
        body: 'Olá, {{1}}.\nVocê tem um pagamento no valor de {{2}} cuja data de vencimento é {{3}}. Para sua comodidade, anexamos uma cópia da sua fatura.',
        variableLabels: ['nome do cliente', 'valor', 'data de vencimento'],
        headerType: 'DOCUMENT',
        buttons: [{ type: 'QUICK_REPLY', text: 'Revisar e pagar' }],
        suggestedName: 'fatura_proximo_vencimento',
    },

    // ── PAGAMENTOS: Falha ────────────────────────────
    {
        id: 'payment_failed_1',
        category: 'payments',
        subcategory: 'payment_failed',
        displayName: 'Falha no Pagamento #1',
        subcategoryDisplayName: 'Rejeição/falha no pagamento',
        body: 'Oi, {{1}},\n\nNão foi possível processar o pagamento de {{2}} para a conta {{3}}.\n\nVerifique sua conta e tente novamente.',
        variableLabels: ['nome do cliente', 'valor', 'conta'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver conta' }],
        suggestedName: 'falha_pagamento_1',
    },
    {
        id: 'payment_failed_4',
        category: 'payments',
        subcategory: 'payment_failed',
        displayName: 'Falha na Fatura',
        subcategoryDisplayName: 'Rejeição/falha no pagamento',
        body: 'Olá, {{1}}, não foi possível processar o pagamento da sua fatura {{2}}. Tente novamente ou entre em contato com nossa equipe de suporte.',
        variableLabels: ['nome do cliente', 'número da fatura'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Pagar agora' }],
        suggestedName: 'falha_fatura',
    },

    // ── PAGAMENTOS: Aviso ────────────────────────────
    {
        id: 'payment_notice_1',
        category: 'payments',
        subcategory: 'payment_notice',
        displayName: 'Aviso de Pagamento Programado',
        subcategoryDisplayName: 'Aviso de pagamento',
        body: 'Seu pagamento no valor de {{1}} será processado no dia {{2}}.\n\nObrigado.',
        variableLabels: ['valor', 'data do processamento'],
        headerType: 'NONE',
        buttons: [],
        suggestedName: 'aviso_pagamento_programado',
    },
    {
        id: 'payment_notice_2',
        category: 'payments',
        subcategory: 'payment_notice',
        displayName: 'Agradecimento de Pagamento',
        subcategoryDisplayName: 'Aviso de pagamento',
        body: 'Agradecemos pelo pagamento no valor de {{1}}.\n\nA {{2}} será feita no dia {{3}}.',
        variableLabels: ['valor', 'ação/entrega', 'data'],
        headerType: 'NONE',
        buttons: [],
        suggestedName: 'agradecimento_pagamento',
    },
    {
        id: 'payment_notice_3',
        category: 'payments',
        subcategory: 'payment_notice',
        displayName: 'Aviso de Cobrança Futura',
        subcategoryDisplayName: 'Aviso de pagamento',
        body: 'Olá {{1}}, informamos que uma cobrança de {{2}} referente a {{3}} será realizada em {{4}}.\n\nQualquer dúvida, entre em contato.',
        variableLabels: ['nome do cliente', 'valor', 'descrição', 'data'],
        headerType: 'NONE',
        buttons: [],
        suggestedName: 'aviso_cobranca_futura',
    },

    // ── PAGAMENTOS: Pagamento em atraso ──────────────
    {
        id: 'late_payment_1',
        category: 'payments',
        subcategory: 'late_payment',
        displayName: 'Pagamento em Atraso #1',
        subcategoryDisplayName: 'Pagamento em atraso',
        body: 'Olá {{1}}, identificamos que o pagamento de {{2}} referente a {{3}} está em atraso desde {{4}}.\n\nRegularize para evitar multas e juros.',
        variableLabels: ['nome do cliente', 'valor', 'descrição/fatura', 'data de vencimento'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Pagar agora' }],
        suggestedName: 'pagamento_em_atraso_1',
    },
    {
        id: 'late_payment_2',
        category: 'payments',
        subcategory: 'late_payment',
        displayName: 'Pagamento em Atraso — Última Chance',
        subcategoryDisplayName: 'Pagamento em atraso',
        body: 'Atenção, {{1}}!\n\nSeu pagamento de {{2}} está {{3}} dias em atraso. Para evitar a suspensão do serviço, efetue o pagamento até {{4}}.',
        variableLabels: ['nome do cliente', 'valor', 'dias em atraso', 'data limite'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Pagar agora' }],
        suggestedName: 'pagamento_em_atraso_2',
    },
    {
        id: 'late_payment_3',
        category: 'payments',
        subcategory: 'late_payment',
        displayName: 'Cobrança por Atraso',
        subcategoryDisplayName: 'Pagamento em atraso',
        body: 'Olá {{1}}, seu pagamento de {{2}} referente a {{3}} não foi identificado.\n\nTotal com encargos: {{4}}.\n\nRegularize agora.',
        variableLabels: ['nome do cliente', 'valor original', 'descrição', 'valor com encargos'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Negociar débito' }],
        suggestedName: 'cobranca_atraso',
    },

    // ── PAGAMENTOS: Pagamento programado ─────────────
    {
        id: 'scheduled_payment_1',
        category: 'payments',
        subcategory: 'scheduled_payment',
        displayName: 'Pagamento Programado Confirmado',
        subcategoryDisplayName: 'Pagamento programado',
        body: 'Olá {{1}}, seu pagamento de {{2}} foi programado para {{3}}.\n\nVocê receberá uma confirmação após o processamento.',
        variableLabels: ['nome do cliente', 'valor', 'data'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver detalhes' }],
        suggestedName: 'pagamento_programado_1',
    },
    {
        id: 'scheduled_payment_2',
        category: 'payments',
        subcategory: 'scheduled_payment',
        displayName: 'Lembrete de Pagamento Programado',
        subcategoryDisplayName: 'Pagamento programado',
        body: 'Lembrete, {{1}}:\n\nSeu pagamento de {{2}} para {{3}} está programado para amanhã, {{4}}.\n\nCertifique-se de que há saldo suficiente.',
        variableLabels: ['nome do cliente', 'valor', 'descrição', 'data'],
        headerType: 'NONE',
        buttons: [],
        suggestedName: 'lembrete_pagamento_programado',
    },
    {
        id: 'scheduled_payment_3',
        category: 'payments',
        subcategory: 'scheduled_payment',
        displayName: 'Cancelar Pagamento Programado',
        subcategoryDisplayName: 'Pagamento programado',
        body: 'Olá {{1}}, seu pagamento programado de {{2}} para {{3}} foi cancelado a seu pedido.\n\nSe precisar reagendar, acesse sua conta.',
        variableLabels: ['nome do cliente', 'valor', 'descrição'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Reagendar' }],
        suggestedName: 'cancelar_pagamento_programado',
    },

    // ── PAGAMENTOS: Pagamento realizado ───────────────
    {
        id: 'payment_success_1',
        category: 'payments',
        subcategory: 'payment_success',
        displayName: 'Pagamento Realizado com Sucesso',
        subcategoryDisplayName: 'Pagamento realizado com sucesso',
        body: 'Olá {{1}}, seu pagamento de {{2}} referente a {{3}} foi realizado com sucesso em {{4}}.\n\nObrigado!',
        variableLabels: ['nome do cliente', 'valor', 'descrição', 'data'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver comprovante' }],
        suggestedName: 'pagamento_realizado_sucesso',
    },

    // ── PAGAMENTOS: Anexo de recibo ───────────────────
    {
        id: 'receipt_attachment_1',
        category: 'payments',
        subcategory: 'receipt_attachment',
        displayName: 'Recibo de Pagamento',
        subcategoryDisplayName: 'Anexo de recibo',
        body: 'Olá {{1}}, segue o recibo do seu pagamento de {{2}} realizado em {{3}}.\n\nGuarde este comprovante para consultas futuras.',
        variableLabels: ['nome do cliente', 'valor', 'data'],
        headerType: 'DOCUMENT',
        buttons: [],
        suggestedName: 'recibo_pagamento_1',
    },
    {
        id: 'receipt_attachment_2',
        category: 'payments',
        subcategory: 'receipt_attachment',
        displayName: 'Recibo de Fatura',
        subcategoryDisplayName: 'Anexo de recibo',
        body: 'Olá {{1}}, sua fatura {{2}} referente a {{3}} está disponível. Valor: {{4}}.',
        variableLabels: ['nome do cliente', 'número da fatura', 'descrição', 'valor'],
        headerType: 'DOCUMENT',
        buttons: [{ type: 'QUICK_REPLY', text: 'Pagar fatura' }],
        suggestedName: 'recibo_fatura',
    },
    {
        id: 'receipt_attachment_3',
        category: 'payments',
        subcategory: 'receipt_attachment',
        displayName: 'Comprovante de Transferência',
        subcategoryDisplayName: 'Anexo de recibo',
        body: 'Olá {{1}}, a transferência de {{2}} para {{3}} foi concluída. Segue o comprovante em anexo.',
        variableLabels: ['nome do cliente', 'valor', 'destinatário'],
        headerType: 'DOCUMENT',
        buttons: [],
        suggestedName: 'comprovante_transferencia',
    },

    // ── PAGAMENTOS: Recarga ───────────────────────────
    {
        id: 'topup_failure_1',
        category: 'payments',
        subcategory: 'topup_failure',
        displayName: 'Falha na Recarga',
        subcategoryDisplayName: 'Rejeição/falha na recarga',
        body: 'Olá {{1}}, sua recarga de {{2}} para o número {{3}} não foi processada.\n\nMotivo: {{4}}.\n\nTente novamente ou entre em contato.',
        variableLabels: ['nome do cliente', 'valor', 'número', 'motivo da falha'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Tentar novamente' }],
        suggestedName: 'falha_recarga',
    },
    {
        id: 'topup_confirmation_1',
        category: 'payments',
        subcategory: 'topup_confirmation',
        displayName: 'Recarga Confirmada',
        subcategoryDisplayName: 'Confirmação de recarga',
        body: 'Olá {{1}}, sua recarga de {{2}} para o número {{3}} foi realizada com sucesso!\n\nNovo saldo: {{4}}.',
        variableLabels: ['nome do cliente', 'valor recarregado', 'número', 'novo saldo'],
        headerType: 'NONE',
        buttons: [],
        suggestedName: 'confirmacao_recarga',
    },

    // ── PAGAMENTOS: Extrato disponível ────────────────
    {
        id: 'statement_available_1',
        category: 'payments',
        subcategory: 'statement_available',
        displayName: 'Extrato Mensal Disponível',
        subcategoryDisplayName: 'Extrato disponível',
        body: 'Olá {{1}}, seu extrato de {{2}} está disponível.\n\nAcesse sua conta para visualizar todas as movimentações do período.',
        variableLabels: ['nome do cliente', 'mês/período'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver extrato' }],
        suggestedName: 'extrato_mensal_disponivel',
    },
    {
        id: 'statement_available_2',
        category: 'payments',
        subcategory: 'statement_available',
        displayName: 'Extrato com Anexo',
        subcategoryDisplayName: 'Extrato disponível',
        body: 'Olá {{1}}, seu extrato referente a {{2}} está disponível em anexo.\n\nTotal de movimentações: {{3}}. Saldo final: {{4}}.',
        variableLabels: ['nome do cliente', 'período', 'número de movimentações', 'saldo final'],
        headerType: 'DOCUMENT',
        buttons: [],
        suggestedName: 'extrato_com_anexo',
    },

    // ── GERENCIAMENTO DE PEDIDOS: Atualização sobre a entrega ──
    {
        id: 'address_update',
        category: 'orders',
        subcategory: 'delivery_update',
        displayName: 'Endereço de Entrega Atualizado',
        subcategoryDisplayName: 'Atualização sobre a entrega',
        body: 'Olá {{1}}, seu endereço de entrega foi atualizado com sucesso para {{2}}. Entre em contato pelo {{3}} para qualquer dúvida.',
        variableLabels: ['nome do cliente', 'novo endereço', 'contato'],
        headerType: 'NONE',
        buttons: [],
        suggestedName: 'address_update',
    },
    {
        id: 'delivery_update_1',
        category: 'orders',
        subcategory: 'delivery_update',
        displayName: 'Pedido a Caminho (com aviso adulto)',
        subcategoryDisplayName: 'Atualização sobre a entrega',
        body: 'Olá {{1}}, seu pedido {{2}} está a caminho e deve chegar em breve.\n\nEntrega estimada: {{3}}\n\nAvisaremos quando o pedido for entregue.\nUm adulto deve estar em casa para receber.',
        variableLabels: ['nome do cliente', 'número do pedido', 'horário estimado'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Rastrear pedido' }],
        suggestedName: 'delivery_update_1',
    },
    {
        id: 'delivery_update_2',
        category: 'orders',
        subcategory: 'delivery_update',
        displayName: 'Saiu para Entrega (janela de horário)',
        subcategoryDisplayName: 'Atualização sobre a entrega',
        body: 'Olá {{1}}, seu pedido {{2}} saiu para entrega!\n\nChega {{3}}, entre {{4}} e {{5}}.',
        variableLabels: ['nome do cliente', 'número do pedido', 'dia', 'horário inicial', 'horário final'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Rastrear pedido' }],
        suggestedName: 'delivery_update_2',
    },
    {
        id: 'delivery_update_3',
        category: 'orders',
        subcategory: 'delivery_update',
        displayName: 'Saiu para Entrega (previsão)',
        subcategoryDisplayName: 'Atualização sobre a entrega',
        body: 'Seu pedido {{1}} saiu para entrega!\n\nPrevisão de chegada: {{2}}.\n\nObrigado pela preferência.',
        variableLabels: ['número do pedido', 'data prevista'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Rastrear pedido' }],
        suggestedName: 'delivery_update_3',
    },
    {
        id: 'delivery_update_4',
        category: 'orders',
        subcategory: 'delivery_update',
        displayName: 'Saiu para Entrega (chegada prevista)',
        subcategoryDisplayName: 'Atualização sobre a entrega',
        body: 'Seu pedido {{1}} saiu para entrega e a previsão de chegada é {{2}}.\n\nObrigado pela preferência.',
        variableLabels: ['número do pedido', 'data prevista'],
        headerType: 'NONE',
        buttons: [],
        suggestedName: 'delivery_update_4',
    },

    // ── GERENCIAMENTO DE PEDIDOS: Confirmação de entrega ──
    {
        id: 'delivery_confirmation_1',
        category: 'orders',
        subcategory: 'delivery_confirmation',
        displayName: 'Pedido Entregue #1',
        subcategoryDisplayName: 'Confirmação de entrega',
        body: 'Olá {{1}}, seu pedido {{2}} foi entregue com sucesso!\n\nVocê pode gerenciar seu pedido abaixo.',
        variableLabels: ['nome do cliente', 'número do pedido'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Gerenciar pedido' }],
        suggestedName: 'delivery_confirmation_1',
    },
    {
        id: 'delivery_confirmation_2',
        category: 'orders',
        subcategory: 'delivery_confirmation',
        displayName: 'Pedido Entregue — Devolução',
        subcategoryDisplayName: 'Confirmação de entrega',
        body: 'Olá {{1}}, seu pedido {{2}} foi entregue.\n\nPrecisa devolver ou trocar algum item?\nClique para gerenciar seu pedido.',
        variableLabels: ['nome do cliente', 'número do pedido'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Gerenciar pedido' }],
        suggestedName: 'delivery_confirmation_2',
    },
    {
        id: 'delivery_confirmation_3',
        category: 'orders',
        subcategory: 'delivery_confirmation',
        displayName: 'Pedido Entregue — Iniciar Devolução',
        subcategoryDisplayName: 'Confirmação de entrega',
        body: '{{1}}, seu pedido {{2}} foi entregue em {{3}}.\n\nSe precisar devolver ou trocar algum item, clique abaixo.',
        variableLabels: ['nome do cliente', 'número do pedido', 'data de entrega'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Iniciar devolução' }],
        suggestedName: 'delivery_confirmation_3',
    },
    {
        id: 'delivery_confirmation_4',
        category: 'orders',
        subcategory: 'delivery_confirmation',
        displayName: 'Pedido Entregue — Agradecimento',
        subcategoryDisplayName: 'Confirmação de entrega',
        body: '{{1}}, seu pedido foi entregue com sucesso em {{2}}.\n\nObrigado pela sua compra.',
        variableLabels: ['nome do cliente', 'data de entrega'],
        headerType: 'NONE',
        buttons: [],
        suggestedName: 'delivery_confirmation_4',
    },
    {
        id: 'delivery_confirmation_5',
        category: 'orders',
        subcategory: 'delivery_confirmation',
        displayName: 'Pedido Entregue — Ver Pedido',
        subcategoryDisplayName: 'Confirmação de entrega',
        body: 'Olá {{1}},\n\nÓtima notícia! Seu pedido {{2}} foi entregue.',
        variableLabels: ['nome do cliente', 'número do pedido'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver pedido' }],
        suggestedName: 'delivery_confirmation_5',
    },

    // ── GERENCIAMENTO DE PEDIDOS: Confirmação do pedido ──
    {
        id: 'order_confirmed',
        category: 'orders',
        subcategory: 'order_confirmation',
        displayName: 'Pedido em Preparação',
        subcategoryDisplayName: 'Confirmação do pedido',
        body: 'Olá {{1}},\nEstamos preparando seu pedido {{2}} e avisaremos quando estiver a caminho.',
        variableLabels: ['nome do cliente', 'número do pedido'],
        headerType: 'NONE',
        buttons: [],
        suggestedName: 'order_confirmed',
    },
    {
        id: 'order_delivered',
        category: 'orders',
        subcategory: 'order_confirmation',
        displayName: 'Pedido Entregue — Simples',
        subcategoryDisplayName: 'Confirmação do pedido',
        body: 'Olá {{1}},\nSeu {{2}} foi entregue. Obrigado por comprar conosco.',
        variableLabels: ['nome do cliente', 'produto/pedido'],
        headerType: 'NONE',
        buttons: [],
        suggestedName: 'order_delivered',
    },
    {
        id: 'order_confirm_auto_schedule',
        category: 'orders',
        subcategory: 'order_confirmation',
        displayName: 'Pedido Confirmado — Agendamento Automático',
        subcategoryDisplayName: 'Confirmação do pedido',
        body: 'Olá {{1}}, seu pedido de {{2}} foi confirmado com sucesso! Agendamos uma visita para {{3}} no seu endereço. Confirme se esse horário funciona para você.',
        variableLabels: ['nome do cliente', 'produto/serviço', 'data e hora'],
        headerType: 'NONE',
        buttons: [
            { type: 'QUICK_REPLY', text: 'Confirmar' },
            { type: 'QUICK_REPLY', text: 'Reagendar' },
        ],
        suggestedName: 'order_confirm_auto_schedule',
    },
    {
        id: 'order_confirm_manual_schedule',
        category: 'orders',
        subcategory: 'order_confirmation',
        displayName: 'Pedido Confirmado — Agendamento Manual',
        subcategoryDisplayName: 'Confirmação do pedido',
        body: 'Olá {{1}}, seu pedido de {{2}} foi confirmado! Responda *Agendar* para escolher o horário da sua visita.',
        variableLabels: ['nome do cliente', 'produto/serviço'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Agendar' }],
        suggestedName: 'order_confirm_manual_schedule',
    },
    {
        id: 'order_management_1',
        category: 'orders',
        subcategory: 'order_confirmation',
        displayName: 'Confirmação Completa com Entrega',
        subcategoryDisplayName: 'Confirmação do pedido',
        body: 'Olá {{1}},\n\nObrigado pelo seu {{2}}! Seu número de pedido é {{3}}.\n\nEstamos separando o {{4}} para envio.\n\nEntrega estimada: {{5}}.\n\nAvisaremos quando o pedido for enviado.',
        variableLabels: ['nome do cliente', 'compra/produto', 'número do pedido', 'produto', 'data estimada'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver detalhes do pedido' }],
        suggestedName: 'order_management_1',
    },
    {
        id: 'order_management_2',
        category: 'orders',
        subcategory: 'order_confirmation',
        displayName: 'Confirmado com Número e Prazo',
        subcategoryDisplayName: 'Confirmação do pedido',
        body: 'Olá {{1}}, seu pedido está confirmado e o número é {{2}}.\n\nEntrega estimada: {{3}}.\n\nEnviaremos mais detalhes em breve.',
        variableLabels: ['nome do cliente', 'número do pedido', 'data estimada'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver detalhes do pedido' }],
        suggestedName: 'order_management_2',
    },
    {
        id: 'order_management_3',
        category: 'orders',
        subcategory: 'order_confirmation',
        displayName: 'Pedido Recebido — Gerenciar',
        subcategoryDisplayName: 'Confirmação do pedido',
        body: 'Olá {{1}}, recebemos seu pedido.\n\nNúmero do pedido: {{2}}.\nEntrega estimada: {{3}}.\n\nClique abaixo para gerenciar seu pedido.',
        variableLabels: ['nome do cliente', 'número do pedido', 'data estimada'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Gerenciar pedido' }],
        suggestedName: 'order_management_3',
    },
    {
        id: 'order_management_4',
        category: 'orders',
        subcategory: 'order_confirmation',
        displayName: 'Pedido em Processamento',
        subcategoryDisplayName: 'Confirmação do pedido',
        body: 'Olá {{1}},\nSeu pedido foi realizado com sucesso e está sendo processado. Número do pedido: {{2}}. Veja os detalhes abaixo.',
        variableLabels: ['nome do cliente', 'número do pedido'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Ver pedido' }],
        suggestedName: 'order_management_4',
    },
    {
        id: 'order_management_5',
        category: 'orders',
        subcategory: 'order_confirmation',
        displayName: 'Aguardando Pagamento',
        subcategoryDisplayName: 'Confirmação do pedido',
        body: 'Olá {{1}},\n\nRecebemos seu pedido {{2}}. Enviaremos uma atualização assim que o pagamento for aprovado.\n\nObrigado por comprar conosco!',
        variableLabels: ['nome do cliente', 'número do pedido'],
        headerType: 'NONE',
        buttons: [{ type: 'QUICK_REPLY', text: 'Detalhes do pedido' }],
        suggestedName: 'order_management_5',
    },

    // ── GERENCIAMENTO DE PEDIDOS: Instalação/Serviço ──
    {
        id: 'installation_complete',
        category: 'orders',
        subcategory: 'delivery_confirmation',
        displayName: 'Instalação Concluída',
        subcategoryDisplayName: 'Confirmação de entrega',
        body: 'Olá {{1}}, sua instalação de {{2}} foi concluída! Nosso técnico configurou sua conexão e você já pode usar. Se tiver algum problema, responda esta mensagem ou entre em contato pelo {{3}}.',
        variableLabels: ['nome do cliente', 'produto/serviço instalado', 'contato de suporte'],
        headerType: 'NONE',
        buttons: [],
        suggestedName: 'installation_complete',
    },
];
